# Generated by Django 2.1.7 on 2019-07-31 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordcount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date publish'),
        ),
    ]
